// ========== 模拟AI识别数据 ==========

const MOCK_DATA = {
  fridge1: {
    ingredients: [
      { name: '鸡蛋', emoji: '🥚', freshness: '新鲜', amount: '6个' },
      { name: '西红柿', emoji: '🍅', freshness: '新鲜', amount: '3个' },
      { name: '青椒', emoji: '🫑', freshness: '新鲜', amount: '4个' },
      { name: '五花肉', emoji: '🥩', freshness: '需尽快食用', amount: '300g' },
      { name: '大葱', emoji: '🧅', freshness: '新鲜', amount: '2根' },
      { name: '大蒜', emoji: '🧄', freshness: '新鲜', amount: '1头' },
      { name: '老抽', emoji: '🫙', freshness: '充足', amount: '半瓶' },
    ],
    recipes: [
      {
        id: 'r1',
        name: '西红柿炒鸡蛋',
        emoji: '🍳',
        time: '10分钟',
        difficulty: '简单',
        calories: '180千卡',
        tags: ['快手菜', '家常'],
        match: ['鸡蛋', '西红柿', '大葱'],
        missing: [],
        steps: [
          '鸡蛋打散，加少许盐搅匀；西红柿切块',
          '热油锅，倒入蛋液炒至凝固盛出',
          '锅中加油，放入西红柿翻炒出汁',
          '倒回鸡蛋，加盐、少许糖调味，撒葱花出锅',
        ],
      },
      {
        id: 'r2',
        name: '青椒肉丝',
        emoji: '🫑',
        time: '15分钟',
        difficulty: '简单',
        calories: '260千卡',
        tags: ['快手菜', '下饭'],
        match: ['青椒', '五花肉', '大蒜', '老抽'],
        missing: ['瘦肉（可用五花肉代替）'],
        steps: [
          '五花肉切丝，加生抽、淀粉腌制5分钟',
          '青椒去籽切丝，蒜切末',
          '热锅少油，下肉丝煸炒至变色',
          '加入蒜末、青椒丝大火翻炒1分钟，加盐和老抽调味',
        ],
      },
      {
        id: 'r3',
        name: '回锅肉',
        emoji: '🥘',
        time: '25分钟',
        difficulty: '中等',
        calories: '350千卡',
        tags: ['硬菜', '下饭', '川味'],
        match: ['五花肉', '青椒', '大葱', '大蒜'],
        missing: ['郫县豆瓣酱', '姜'],
        steps: [
          '五花肉冷水下锅，加姜片、料酒煮至8成熟，捞出切片',
          '青椒切块，蒜切片',
          '热锅少油，下肉片煸炒出油至微卷',
          '加豆瓣酱炒出红油，放青椒、蒜片、葱段翻炒均匀',
        ],
      },
      {
        id: 'r4',
        name: '番茄蛋花汤',
        emoji: '🍜',
        time: '10分钟',
        difficulty: '简单',
        calories: '90千卡',
        tags: ['汤羹', '快手菜'],
        match: ['鸡蛋', '西红柿', '大葱'],
        missing: [],
        steps: [
          '西红柿切块，鸡蛋打散备用',
          '锅中加水烧开，放入西红柿煮3分钟',
          '淋入蛋液，搅拌成蛋花',
          '加盐、香油、葱花调味即可',
        ],
      },
    ],
  },

  fridge2: {
    ingredients: [
      { name: '鸡胸肉', emoji: '🍗', freshness: '新鲜', amount: '2块' },
      { name: '西兰花', emoji: '🥦', freshness: '新鲜', amount: '1颗' },
      { name: '胡萝卜', emoji: '🥕', freshness: '新鲜', amount: '2根' },
      { name: '土豆', emoji: '🥔', freshness: '新鲜', amount: '3个' },
      { name: '洋葱', emoji: '🧅', freshness: '新鲜', amount: '1个' },
      { name: '蒜', emoji: '🧄', freshness: '新鲜', amount: '几瓣' },
      { name: '生抽', emoji: '🫙', freshness: '充足', amount: '半瓶' },
      { name: '黑胡椒', emoji: '🧂', freshness: '充足', amount: '有' },
    ],
    recipes: [
      {
        id: 'r5',
        name: '香煎鸡胸肉配西兰花',
        emoji: '🥗',
        time: '15分钟',
        difficulty: '简单',
        calories: '220千卡',
        tags: ['减脂', '快手菜', '高蛋白'],
        match: ['鸡胸肉', '西兰花', '胡萝卜', '蒜', '黑胡椒'],
        missing: ['橄榄油'],
        steps: [
          '鸡胸肉用刀背拍松，加盐、黑胡椒、生抽腌制5分钟',
          '西兰花切小朵，胡萝卜切片，焯水备用',
          '热锅少油，鸡胸肉中火每面煎3-4分钟至金黄',
          '盛出切片，搭配蔬菜装盘',
        ],
      },
      {
        id: 'r6',
        name: '土豆胡萝卜炖鸡块',
        emoji: '🍲',
        time: '30分钟',
        difficulty: '中等',
        calories: '310千卡',
        tags: ['硬菜', '下饭'],
        match: ['鸡胸肉', '土豆', '胡萝卜', '洋葱', '蒜', '生抽'],
        missing: ['料酒', '八角'],
        steps: [
          '鸡胸肉切块，土豆胡萝卜切滚刀块',
          '热油爆香洋葱、蒜片，下鸡块翻炒至变色',
          '加入土豆胡萝卜，倒水没过食材',
          '加生抽、盐，大火烧开转小火炖20分钟，收汁出锅',
        ],
      },
      {
        id: 'r7',
        name: '西兰花鸡胸肉沙拉',
        emoji: '🥙',
        time: '10分钟',
        difficulty: '简单',
        calories: '160千卡',
        tags: ['减脂', '快手菜', '轻食'],
        match: ['鸡胸肉', '西兰花', '胡萝卜', '黑胡椒'],
        missing: ['沙拉酱/油醋汁'],
        steps: [
          '鸡胸肉水煮或煎熟，切薄片',
          '西兰花、胡萝卜焯水至断生',
          '混合食材，淋上油醋汁，撒黑胡椒即可',
        ],
      },
    ],
  },

  fridge3: {
    ingredients: [
      { name: '豆腐', emoji: '🧈', freshness: '新鲜', amount: '1块' },
      { name: '牛肉', emoji: '🥩', freshness: '新鲜', amount: '250g' },
      { name: '洋葱', emoji: '🧅', freshness: '新鲜', amount: '2个' },
      { name: '青葱', emoji: '🧅', freshness: '新鲜', amount: '一把' },
      { name: '姜', emoji: '🫚', freshness: '新鲜', amount: '1块' },
      { name: '蒜', emoji: '🧄', freshness: '新鲜', amount: '几瓣' },
      { name: '生抽', emoji: '🫙', freshness: '充足', amount: '有' },
      { name: '蚝油', emoji: '🫙', freshness: '充足', amount: '有' },
    ],
    recipes: [
      {
        id: 'r8',
        name: '麻婆豆腐',
        emoji: '🌶️',
        time: '20分钟',
        difficulty: '中等',
        calories: '280千卡',
        tags: ['硬菜', '下饭', '川味'],
        match: ['豆腐', '牛肉', '姜', '蒜', '青葱', '生抽'],
        missing: ['郫县豆瓣酱', '花椒粉'],
        steps: [
          '豆腐切2cm方块，焯水去腥',
          '牛肉剁成肉末，姜蒜切末',
          '热油炒牛肉末至变色，加豆瓣酱炒出红油',
          '加姜蒜末、水烧开，放入豆腐小火煮5分钟，勾芡撒花椒粉和葱花',
        ],
      },
      {
        id: 'r9',
        name: '洋葱炒牛肉',
        emoji: '🧅',
        time: '15分钟',
        difficulty: '简单',
        calories: '250千卡',
        tags: ['快手菜', '下饭', '高蛋白'],
        match: ['牛肉', '洋葱', '姜', '生抽', '蚝油'],
        missing: ['料酒', '淀粉'],
        steps: [
          '牛肉逆纹切薄片，加生抽、蚝油、淀粉腌制10分钟',
          '洋葱切丝',
          '热锅多油，牛肉滑炒至变色盛出',
          '锅中留底油炒洋葱至透明，倒回牛肉翻炒均匀出锅',
        ],
      },
      {
        id: 'r10',
        name: '家常豆腐煲',
        emoji: '🍲',
        time: '25分钟',
        difficulty: '简单',
        calories: '230千卡',
        tags: ['家常', '汤羹'],
        match: ['豆腐', '牛肉', '青葱', '姜', '蒜', '生抽'],
        missing: ['香菇', '白菜（可选）'],
        steps: [
          '豆腐切厚片，两面煎至金黄',
          '牛肉末加姜蒜炒香，加生抽和水煮开',
          '放入煎好的豆腐，小火炖8分钟入味',
          '撒葱花出锅',
        ],
      },
      {
        id: 'r11',
        name: '葱爆牛肉',
        emoji: '🥩',
        time: '12分钟',
        difficulty: '简单',
        calories: '270千卡',
        tags: ['快手菜', '高蛋白', '下饭'],
        match: ['牛肉', '青葱', '姜', '生抽', '蚝油', '蒜'],
        missing: [],
        steps: [
          '牛肉切薄片，加生抽蚝油姜丝腌制',
          '大葱斜切段',
          '热锅大火，爆香蒜片，下牛肉快速翻炒30秒',
          '加入葱段翻炒至断生即可出锅',
        ],
      },
    ],
  },
};

const CALORIE_MOCK_DATA = {
  meal1: {
    totalCalories: 850,
    totalProtein: 42,
    totalCarbs: 115,
    totalFat: 28,
    items: [
      { name: '米饭', emoji: '🍚', calories: 280, protein: 6, carbs: 62, fat: 1, portion: '约200g' },
      { name: '番茄炒蛋', emoji: '🍳', calories: 180, protein: 10, carbs: 12, fat: 10, portion: '约150g' },
      { name: '红烧肉', emoji: '🥩', calories: 350, protein: 18, carbs: 8, fat: 28, portion: '约120g' },
      { name: '炒青菜', emoji: '🥬', calories: 40, protein: 2, carbs: 5, fat: 0.5, portion: '约100g' },
    ],
    advice: '碳水摄入偏高（米饭+番茄炒蛋双重碳水），建议米饭减半或替换为杂粮。蛋白质充足，脂肪主要来自红烧肉，适度可控。整体搭配合理，一餐热量适中。',
  },
  meal2: {
    totalCalories: 520,
    totalProtein: 38,
    totalCarbs: 45,
    totalFat: 18,
    items: [
      { name: '鸡胸肉沙拉', emoji: '🥗', calories: 220, protein: 28, carbs: 12, fat: 8, portion: '约250g' },
      { name: '牛油果', emoji: '🥑', calories: 160, protein: 2, carbs: 9, fat: 15, portion: '半个' },
      { name: '水煮蛋', emoji: '🥚', calories: 75, protein: 7, carbs: 1, fat: 10, portion: '1个' },
      { name: '全麦面包', emoji: '🍞', calories: 65, protein: 3, carbs: 13, fat: 1, portion: '1片' },
    ],
    advice: '优秀的减脂餐搭配！高蛋白低碳水，牛油果提供优质脂肪。如果目标是增肌，可增加一片全麦面包或半碗糙米饭补充碳水。',
  },
  meal3: {
    totalCalories: 1200,
    totalProtein: 55,
    totalCarbs: 130,
    totalFat: 52,
    items: [
      { name: '火锅锅底(麻辣)', emoji: '🫕', calories: 300, protein: 5, carbs: 15, fat: 24, portion: '约500ml' },
      { name: '肥牛卷', emoji: '🥩', calories: 350, protein: 22, carbs: 0, fat: 28, portion: '约150g' },
      { name: '豆腐', emoji: '🧈', calories: 80, protein: 8, carbs: 3, fat: 4, portion: '约100g' },
      { name: '蔬菜拼盘', emoji: '🥬', calories: 60, protein: 3, carbs: 10, fat: 0.5, portion: '约200g' },
      { name: '面条', emoji: '🍜', calories: 220, protein: 8, carbs: 45, fat: 1.5, portion: '约100g' },
      { name: '蘸料(麻酱)', emoji: '🥣', calories: 190, protein: 3, carbs: 5, fat: 18, portion: '约30g' },
    ],
    advice: '火锅热量炸弹！麻辣锅底+麻酱蘸料贡献了大量隐形脂肪，肥牛虽蛋白质丰富但脂肪含量也高。建议换清汤锅底，蘸料改用醋+蒜泥+少量酱油，蔬菜多吃、面条减半。',
  },
};
